services:
  backend:
    container_name: backend
    build: ./cmd
    networks:
      - internal-net
    environment:
      - OPENWEATHERMAP_API_KEY=fillme

  nginx:
    build: 
      context: nginx
    container_name: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d/
    networks: 
      - internal-net
    ports: 
      - "8080:80"
    depends_on:
      - backend

networks:
  internal-net: